// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmB4cvUuiR5Ry8yjjOP4Z7rjz1KbTJY4w',
    appId: '1:248259965172:web:8c62c3fbfb58f58d146ea1',
    messagingSenderId: '248259965172',
    projectId: 'cura-health-aabdb',
    authDomain: 'cura-health-aabdb.firebaseapp.com',
    storageBucket: 'cura-health-aabdb.appspot.com',
    measurementId: 'G-2DXNTYEZ7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwK-IRp7pDeG26ldvtOyY0ltcfInEUv-I',
    appId: '1:248259965172:android:6fd2197c4900dc06146ea1',
    messagingSenderId: '248259965172',
    projectId: 'cura-health-aabdb',
    storageBucket: 'cura-health-aabdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7HGfYkTKrM2yoj2hT1oZm6y8jhIlPX8c',
    appId: '1:248259965172:ios:219f50f58800e965146ea1',
    messagingSenderId: '248259965172',
    projectId: 'cura-health-aabdb',
    storageBucket: 'cura-health-aabdb.appspot.com',
    iosBundleId: 'com.example.curaHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7HGfYkTKrM2yoj2hT1oZm6y8jhIlPX8c',
    appId: '1:248259965172:ios:223c308152844a12146ea1',
    messagingSenderId: '248259965172',
    projectId: 'cura-health-aabdb',
    storageBucket: 'cura-health-aabdb.appspot.com',
    iosBundleId: 'com.example.curaHealth.RunnerTests',
  );
}
